### PR TITLE
[IMP] grammar

### PR DESCRIPTION
**Pull request by fhe-odoo**
The en_US police has your back.

### CODE REVIEW

**Comment by fhe-odoo** [comment]
@mart-e Can you check this.

**Comment by mart-e** [comment]
Sure! Thanks for the changes.
Is the 95 -> 90% change necessary?
I don't have problems changing it but it will break the translations so I want to avoid if not necessary.

**Comment by fhe-odoo** [comment]
Up to you. Not mandatory.

**Comment by mart-e** [comment]
Ok, so I will just keep the part with grammar errors.
Merged at 243560be77db5ad842ee3b2a8c498b8ab8a686a4

**Pull request closed without merging**
