### PR TITLE
[REM] *: remove all demo.action buttons from the user documentation

### PR DESCRIPTION
**Pull request by jcs-odoo**
*: accounting, inventory, purchase

@mart-e , would you also remove the code related to the actions?
Cheers :)

Jon

### CODE REVIEW

**Comment by mart-e** [comment]
How about the `demo:fields`? The same problems occures no?

**Comment by jcs-odoo** [comment]
> How about the `demo:fields`? The same problems occures no?
@mart-e 
I didn't know that...
All they do is list all the fields' descriptions in html. They are useless and I didn't know they were causing the same issue. Should I remove them as well?

**Comment by mart-e** [comment]
The issue is maybe a bit less obvious. The problem is that the demo... works on demo.odoo.com which uses the last version of odoo. So when you will rebuild the 13.0 documentation in 2 years, you will list the fields of demo.odoo.com that runs with 15.0. The fields tends to change less often but still it is an issue IMHO.
@AntoineVDV agree?

**Comment by jcs-odoo** [comment]
That makes sense.
I delete them right now :)

**Comment by AntoineVDV** [comment]
> The issue is maybe a bit less obvious. The problem is that the demo... works on demo.odoo.com which uses the last version of odoo. So when you will rebuild the 13.0 documentation in 2 years, you will list the fields of demo.odoo.com that runs with 15.0. The fields tends to change less often but still it is an issue IMHO.
> @AntoineVDV agree?

:+1:

**Pull request merged**
