### PR TITLE
Clarify EWP_SETTINGS error

### PR DESCRIPTION
**Pull request by Ark74**
Describe the issue and adjustments necessary to pass them.

### CODE REVIEW

**Comment by rim-odoo** [comment]
If you think you've found an issue in Odoo, feel free to open a ticket: https://www.odoo.com/help
Not sure that deactivating EWP is really a good piece of advice.

**Comment by Ark74** [comment]
@rim-odoo 
Quoting paypal site:

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/encryptedwebpayments/#encrypted-website-payments-ewp

> Important: The EWP feature is only required to be used for manually created buttons.

And Paypal adviser,

> The EWP Settings are not designed for anyone using a 3rd Party Shopping Cart.

Cheers!

**Comment by Ark74** [comment]
Maybe just mention the matter on the docs?

#=========
* **Encrypted Website Payments & EWP_SETTINGS error**
Please check the [paypal documentation](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/encryptedwebpayments/#encrypted-website-payments-ewp).

#=========

**Comment by rim-odoo** [comment]
> Maybe just mention the matter on the docs?

@Ark74 Indeed, this would be easier :+1:

**Comment by Ark74** [comment]
Closing in favor of https://github.com/odoo/documentation-user/pull/396

**Pull request closed without merging**
