### PR TITLE
Various Odoo.sh documentation fixes

### PR DESCRIPTION
**Pull request by raf-odoo**
Issues encountered while following https://www.odoo.com/documentation/user/13.0/odoo_sh/getting_started/first_module.html . See the commit messages for details.

### CODE REVIEW

**Comment by raf-odoo** [comment]
@rim-odoo These are the remaining Odoo.sh minor issues. I was unable to reproduce the merge conflict issue I mentioned, so I had probably made a mistake somewhere.

**Comment by AntoineVDV** [comment]
@raf-odoo Please prefix your commit titles with the app name. Here "technical" for the one tweaking the config and "odoo.sh" for the others. This has obvious benefits for a developer but more importantly for functional people who will wonder what kind of app "Sphinx" might be ;)

**Comment by raf-odoo** [comment]
> @raf-odoo Please prefix your commit titles with the app name. Here "technical" for those tweaking the config and "odoo.sh" for the others. This has obvious benefits for a developer but more importantly for functional people who will wonder what kind of app "Sphinx" might be ;)

@AntoineVDV Thanks, done :-)

**Comment by raf-odoo** [comment]
@rim-odoo Just saw this is blocked on a review from you, so ping :-)

**Review by rim-odoo — APPROVED** [review]

**Comment by mart-e** [comment]
Hi there !

This commit breaks the nightly doc as we are still using sphinx 1.7 on the cron server.

**Comment by raf-odoo** [comment]
Why is there such a big difference between the Sphinx version in `requirements.txt` and on the server?

**Comment by mart-e** [comment]
> Why is there such a big difference between the Sphinx version in requirements.txt and on the server?

Why is there a requirements.txt ? :smile: 
I have reverted the `add_css_file` at e946532b9b9cc13b2ea3a7ab76e160c3e51c6d98, will set it back once we have update sphinx (hopefully soon)

**Pull request merged**
