### PR TITLE
Translation to Bengla(bn) proposal 

### PR DESCRIPTION
**Pull request by MjAbuz**
@mart-e I need your attention here to start the translation process for user documents to Bengla(bn) .. if we get this in Local language then I guess more users will get interested to use odoo

### CODE REVIEW

**Comment by MjAbuz** [comment]
@mart-e I did requested the language on tranfix log ago, yet not to be seen as approved for translation :(

**Comment by mart-e** [comment]
@MjAbuz I am not sure to understand the content of your PR.

Regarding the addition of new languages for the documentation, we only do it when Odoo is already well translated in the language.
Odoo 13 is translated in Bengali only at 14% and is not translated in 14.0.
Please focus on translating the software first before moving to the documentation (preferably in the latest version).

Closing as nothing to merge.

**Comment by MjAbuz** [comment]
@mart-e odoo14 bengali(bn) project is not yet available for the software, I requested to add Bengali long ago ... that's what I tried to let you know.

**Comment by mart-e** [comment]
https://www.transifex.com/odoo/odoo-14/language/bn/
Was added this morning :)

**Pull request closed without merging**
