### PR TITLE
[REM] sms marketing: remove docs

### PR DESCRIPTION
**Pull request by kbr-odoo**
These pages document very straightforward screens and flows users can easily figure out without dedicated documentation. Besides, those screens are frequently reworked, requiring to maintain the related pages closely. This commit then removes low-value pages to reduce the technical debt and allow focusing on actually useful documentation pages. In addition, the eLearning platform covers the educational needs of the app.
Docs removed:
- contact_lists_and_blacklist.rst
- integrations_and_template.rst
- sms_mailing_reports.rst

### CODE REVIEW

**Comment by Lau-Odoo** [comment]
Hi @kbr-odoo, you forgot to list "overview" in your commit message :) 
The same question as last time, Pricing and Faq is planned to stay there alone or new docs will arrive later?

**Comment by kbr-odoo** [comment]
> Hi @kbr-odoo, you forgot to list "overview" in your commit message :)
> The same question as last time, Pricing and Faq is planned to stay there alone or new docs will arrive later?



> Hi @kbr-odoo, you forgot to list "overview" in your commit message :)
> The same question as last time, Pricing and Faq is planned to stay there alone or new docs will arrive later?

Overview.rst is just for the toctree. It is for the title, not a doc per se. That is why I did not include it.
I don't know if there will be another doc yet.
Thank you, Ludvig!

**Review by Lau-Odoo — APPROVED** [review]

**Comment by Lau-Odoo** [comment]
If there is no other doc, I'm not sure that keeping the faq only in a separate section is very interesting @kbr-odoo 
+ don't forget to resolve conflicts before merging. 😄

**Comment by kbr-odoo** [comment]
> If there is no other doc, I'm not sure that keeping the faq only in a separate section is very interesting @kbr-odoo
> 
> * don't forget to resolve conflicts before merging. 😄

That is an important doc actually. It is about pricing and frequently asked questions.

**Pull request merged**
