### PR TITLE
[IMP] inventory: update an image

### PR DESCRIPTION
**Pull request by dca-odoo**

### CODE REVIEW

**Review by jcs-odoo — CHANGES_REQUESTED** [review]
Hello @dca-odoo ,

I understand this Pull Request is "the second part" of Pull Request #905 

- Since each commit is meant to be "auto-sufficient," I'll close the Pull Request #905 so that all changes are done in one commit, in this Pull Request
- I see that the image you added `virtual_warehouses_08.png` is actually the update in v14.0 of the image `virtual_warehouses_01.png`. There is then no need to add an additional `.....08.png` image. All there is to do is to replace the old image with the new one. The old image will still remain in older versions.
- please rename the commit like this: `[IMP] inventory: update an image`

I see that you created these Pull Requests directly with GitHub, so if you don't know how to do these changes, feel free to ping me if you need assistance in doing these modifications.

Cheers,
Jonathan

**Comment by jcs-odoo** [comment]
Coming back on my first comment, I think now it would be best to rename the image filename since it is new content.

- rename the new image with a relevant filename as [we are just about to add a media filename section](https://github.com/odoo/documentation-user/pull/903/commits/ec6795653a2fd95eee9d781626d1f845cb4afdb1) in our [content guidelines](https://www.odoo.com/documentation/user/14.0/contributing/documentation/content_guidelines.html). For example: `virtual-warehouses-settings.png`.
Cheers

**Comment by dca-odoo** [comment]
Hi @jcs-odoo ,

Thank you for reviewing! I've addressed your comments with the new changes, hopefully it looks okay now!

**Review by jcs-odoo — APPROVED** [review]
Hello @dca-odoo 

Thanks for your changes.
I took the liberty to do some additional changes to your Pull Request:

- squashed your three commits into a single one
- changed the commit message 
- added an alt tag to your image
- deleted the old image

It's good to go, now!
Have a good day!
Jonathan

**Pull request merged**
