### PR TITLE
[IMP] inventory/management/replen._stratergies - update menu path and…

### PR DESCRIPTION
**Pull request by jamescs50**
… screenshot

### CODE REVIEW

**Comment by Lau-Odoo** [comment]
In 13.0, the Reordering Rules menu is still reachable through Master Data @jamescs50

**Comment by jamescs50** [comment]
x-special/nautilus-clipboard
copy
file:///home/james/Pictures/not%20on%20Master%20Data

x-special/nautilus-clipboard
copy
file:///home/james/Pictures/on%20configuration.png

I'm confused - this is not what I am seeing (using runbot)

Also - for future reference - did I raise this merge request correctly? could I have done it better?

**Comment by Lau-Odoo** [comment]
After some investigation, it seems that both of us are right.
In 13.0, the reordering rules menu is still under Master Data.
But, the db you used is a master one (13.4), and the reordering rule menu is changed with the 13.3.

So, yes, you're right but you need to push your branch into 13.3, not 13.0 :)

For future reference, your title is a bit confusing. Maybe try to use something like [IMP] Inventory: min_stock_rule update or something like that :)

**Comment by jamescs50** [comment]
thank you. 
I'm still finding my feet with Odoo - I'll be more careful with the minor versions in future. 
The change is a good one - the menus make more sense this way.

**Comment by AntoineVDV** [comment]
@jamescs50 
> Also - for future reference - did I raise this merge request correctly? could I have done it better?

The clearer the PR, the better. But PR themselves are not that important ;)
What matters is the commit message (it is changed by the reviewer when merging if there is an issue with it) and the code.
If you want to do even better next time, consider:
- A clearer name for the PR. You can still change it now so that future readers know what this PR is about. By default, it takes the content of the commit message which is fine if the latter is well formulated.
- Linking your own issue to the PR so that it is automatically closed. FYI, GitHub has a (feature allowing to do that simply by mentioning it)[https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords].
- Following the guidelines in the `commit_template.txt` file in the root director for the commit message.
- Cropping your tabs bar to only show the page which should be zoomed a bit (~150%).
  Since you used git (and not the GitHub) interface to submit your change you can still do that now:
    1. Update the file (and don't forget to compress it with pngquant)
    2. Run `git add .` to stage the change
    3. Run `git commit --amend` to add the change in your previous commit. Take the opportunity to update the commit message: "[FIX] inventory: correct menuselection to reordering rules menu item"
    4. Run `git push --force` to override the commit(s) listed in this PR with your new ones.

**Comment by AntoineVDV** [comment]
@jamescs50 I just re-targeted this PR to 13.3 (fresh new branch on documentation-user) so a bit of cleaning must be done.
That following commands should do (run them before those of my previous command):
`git fetch origin`
`git checkout 13.0`
`git reset --hard origin/13.3`
`git cherry-pick 113dd88a8372b9eb0b286e107b67dadbc2defbf9`
Check with `git log` and `make clean html` that everything is right
`git push --force`

**Comment by jamescs50** [comment]
I think I may have done a bad and deleted my fork. 

I seem to be unable to commit changes to 13.3. 
This is a small matter and I have learned a lot from the experience. I'll be reading all the documentation very carefully over the next couple of months and if I find anything verifyably wrong with it as at 13.0 I shall make another PR. 
Thanks - and sorry!

**Comment by AntoineVDV** [comment]
The fix still need to be made for 13.3. We can take care of it if you prefer not to or you can close this PR and open another one directly based on 13.3 if you feel like it.

**Pull request closed without merging**
