### PR TITLE
[FIX] portal: remove wrong information and add a link in my portal

### PR DESCRIPTION
**Pull request by jcs-odoo**

### CODE REVIEW

**Comment by jcs-odoo** [comment]
@AntoineVDV 
I couldn't put a 11.0 milestone on this PR.
I know we don't work much on this branch, but the sentence removed is actually wrong.

**Review by rjo-odoo — APPROVED** [review]

**Comment by AntoineVDV** [comment]
> I couldn't put a 11.0 milestone on this PR.

No big deal. We only use milestones to filter PRs more easily from the list view.
Note that this commit won't be forward-ported, but I believe that it is already a back-port of a commit in 12.0 so that's ok.

**Comment by jcs-odoo** [comment]
> > I couldn't put a 11.0 milestone on this PR.
> 
> No big deal. We only use milestones to filter PRs more easily from the list view.
> Note that this commit won't be forward-ported, but I believe that it is already a back-port of a commit in 12.0 so that's ok.

It is not a back port. I can create a second PR for 12.0 if needed, then.

**Comment by jcs-odoo** [comment]
> > I couldn't put a 11.0 milestone on this PR.
> 
> No big deal. We only use milestones to filter PRs more easily from the list view.
> Note that this commit won't be forward-ported, but I believe that it is already a back-port of a commit in 12.0 so that's ok.

PR #863 based on 12.0, so it can also be forward ported to 13.0 and 14.0

Thanks :)

**Comment by AntoineVDV** [comment]
> > > I couldn't put a 11.0 milestone on this PR.
> > 
> > 
> > No big deal. We only use milestones to filter PRs more easily from the list view.
> > Note that this commit won't be forward-ported, but I believe that it is already a back-port of a commit in 12.0 so that's ok.
> 
> It is not a back port. I can create a second PR for 12.0 if needed, then.

Weird. I've definitely seen this sentence being removed but maybe was it from another file.. or the PR is not merged yet :man_shrugging:

**Pull request merged**
