### PR TITLE
11.0 finishing cleanup

### PR DESCRIPTION
**Pull request by nhomar**

### CODE REVIEW

**Comment by nhomar** [comment]
@mart-e All ready to be merged, some fixes done, and finished the error management.

Thanks in advance.

**Comment by mart-e** [comment]
Hi thanks for the changes !
I see there is still screenshots with the mouse cursor on it ;-)

**Comment by nhomar** [comment]
fixing! I'll let you know

**Comment by tivisse** [comment]
Hello @nhomar 

Your PR has been merged at https://github.com/odoo/documentation-user/commit/fa59d94006adb71828fba891c423da4ab79e5344

Have a nice day,

Yannick.

**Pull request closed without merging**
