### PR TITLE
[ADD] searchbar

### PR DESCRIPTION
**Pull request by mart-e**
- [x] Basic Sphinx search
- [x] make it not too ugly

After deployment
- [ ] check multi-language behaviour
- [ ] test search efficiency

### CODE REVIEW

**Comment by jubodoo** [comment]
@rim-odoo Serieux on va avoir un searchbar? :D YESYESYESYES!

**Comment by rim-odoo** [comment]
@jubodoo yep, j'y travaille

**Comment by rim-odoo** [comment]
@mart-e do you have anything against a merge of this?

**Comment by mart-e** [comment]
@rim-odoo r+

**Comment by rim-odoo** [comment]
@mart-e I'll merge it in 11.0, so that we can test it tomorrow, and if it works well, I'll forward port it later to 12.0 and 13.0

**Comment by rim-odoo** [comment]
@jubodoo search bar is available in user doc 11.0, and should be there in 12.0 and 13.0 tomorrow
(works also in other languages if translated)

for future: could be restyled a bit by our fancy designers

**Pull request merged**
