### PR TITLE
[IMP] odoo_sh: Improve odoo.sh spelling

### PR DESCRIPTION
**Pull request by Yenthe666**
@beledouxdenis this are the changes of the spelling. Hope a PR is okay/good.

### CODE REVIEW

**Comment by Yenthe666** [comment]
CC @mart-e

**Comment by mart-e** [comment]
Are you making a PR against a branch that is not merged yet? :thinking: 
Maybe you should contact @beledouxdenis and @dbo-odoo to offer him to check the spellings before it is merged (I don't even know if it is ready) but do not feel I have something to do here.

**Comment by Yenthe666** [comment]
@mart-e he asked me to give feedback on wrong translations and not through comments as @beledouxdenis couldn't track that easily.
So, threw them in a PR, but no feedback. Anyways, always happy to review. 😉

**Comment by dbo-odoo** [comment]
please make a review on the internal pr #267 if you want, but let's not add more complication than necessary :)

**Comment by mart-e** [comment]
Oh I see, you are talking about #267
What Denis said was to go to https://github.com/odoo/documentation-user/pull/267/files, make the comments directly in the code (and not on the commits) using the "Start a review" button (and not "Make a single comment").
This way, people receive only one notification (instead of one mail per comment, kind of spammy) and you see where we still need to correct.

**Comment by Yenthe666** [comment]
Done at https://github.com/odoo/documentation-user/pull/267#pullrequestreview-104865288
Thanks for the feedback & extra info 😉

**Comment by dbo-odoo** [comment]
@mart-e 
PR 267 was not there at the time, there was no PR for that branch, hence why yenthe did his own PR (as implied by the numbering for this one which is 266 :p)
All good then

**Comment by Yenthe666** [comment]
Yeah, basically. Anyways the comments are on the PR now! Thanks guys.

**Pull request closed without merging**
