### PR TITLE
Update my_odoo_portal.rst

### PR DESCRIPTION
**Pull request by ray-odoo**
@jubodoo

### CODE REVIEW

**Comment by AntoineVDV** [comment]
Wouldn't this need to be updated in 12.0 and 13.0, in addition to 14.0?

**Comment by jcs-odoo** [comment]
@ray-odoo @AntoineVDV 
Hello!
I didn't see this PR.
I did a similar change for all versions (11.0 -> 14.0 ) with #862 and #863  but rather than modifying the sentence, I deleted it and added a link to the pricing page, so that it reduces the risk of having contradictions.
What do you think?

**Comment by AntoineVDV** [comment]
I don't have an opinion on the content itself. But the PR should either be closed or re-targeted on 12.0.

**Comment by ray-odoo** [comment]
I have no problem with removing the information about success packs and linking to the pricing pages.

**Comment by jcs-odoo** [comment]
Alright, Thanks then @ray-odoo

**Pull request closed without merging**
