### PR TITLE
[FIX] accounting: fix bad indenting in chile localization

### PR DESCRIPTION
**Pull request by jcs-odoo**
The original PR #745 had errors that led to error messages.

Please forward port in 14.0 as well

### CODE REVIEW

**Comment by AntoineVDV** [comment]
It looks like you rebased your branch on 14.0 rather than 13.0!

**Comment by jcs-odoo** [comment]
> It looks like you rebased your branch on 14.0 rather than 13.0!

My bad, it should be fixed now

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Please update your commit message to:
- Get rid of the version (a commit can live in several versions, mentioning them in the title makes no sense).
- Allow readers to understand quickly what it's about and which files it impacts.

For example ->
> [FIX] accounting: fix bad indenting in chile localization

**Comment by jcs-odoo** [comment]
There it is done.
So where should I mention the forward port to14.0 as well?
Here, as a comment?
Thanks

**Review by AntoineVDV — APPROVED** [review]

**Pull request merged**
