### PR TITLE
[IMP] subscriptions: rename all images

### PR DESCRIPTION
**Pull request by cdu-odoo**

### CODE REVIEW

**Comment by cdu-odoo** [comment]
> The banner has the wrong name (`subscriptions-fs8.png`) and is still 10x too large

Oh my gooood -_-

**Comment by cdu-odoo** [comment]
> The banner has the wrong name (`subscriptions-fs8.png`) and is still 10x too large

Ok it's good now 👍

**Comment by AntoineVDV** [comment]
Good for me, provided that it builds without warning (didn't check).

**Comment by cdu-odoo** [comment]
@AntoineVDV Thank you Antoine :) It was all good

**Pull request merged**
