### PR TITLE
[IMP] website: improved various grammatical errors

### PR DESCRIPTION
**Pull request by ksc-odoo**

### CODE REVIEW

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Please see my review comment on #884

**Comment by ksc-odoo** [comment]
I deleted this documentation, as it falls into the category of being "irrelevant/self-explanatory/already explained in a tutorial video" - this will be the first of many to be deleted for this same reason.

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Hi, please take a look at the discussion in https://github.com/odoo/documentation-user/pull/772 as it gives guidance on how to proceed with page deletion, regarding commits.

Also, you delete `translate.rst` but not the reference to the page in (I suppose) `publish.rst`. I believe that building your branch will yield errors/warnings which must be fixed before merging.

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
You removed the page reference but did not make the commit any clearer.
It should have the [REM] tag and explain why the page is removed since this is quite rare and not obvious at all ;)

**Pull request closed without merging**
