### PR TITLE
[ADD] base_import FAQ

### PR DESCRIPTION
**Pull request by mart-e**
see #157 
cc @csnauwaert

### CODE REVIEW

**Comment by tivisse** [comment]
Shouldn't this be merged into the 9.0 documentation ?

**Comment by tivisse** [comment]
Landed in 9.0 documentation at https://github.com/odoo/documentation-user/commit/0ff269649378de5918247df478a374ad5e265865

**Comment by mart-e** [comment]
No, this should not be in 9.0 ! It is documenting changes in master

**Comment by tivisse** [comment]
Hihi shit

**Comment by tivisse** [comment]
Reverted at https://github.com/odoo/documentation-user/commit/69838f0943345f3085ae93ebfaf05a356ba193a2

I'll let Martin make a second grammar review and modify the data files.

**Comment by nim-odoo** [comment]
This should not be closed (see OPW 687047).
By the way, I would assume that the link https://github.com/odoo/odoo/blob/saas-11/addons/base_import/static/src/xml/import.xml#L11 is wrong (should be "...tation/user/**10.0**/gener...")

**Comment by tivisse** [comment]
Ping @mart-e

**Comment by tivisse** [comment]
Landed in 10.0 at https://github.com/odoo/documentation-user/commit/f90dc23b685158c5ba775fdabfe3ef03db43d28b

**Pull request closed without merging**
